# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f180fccbe138760e8f902bf3f790f3f7e857df68a7c8e98c169d38094b45f7b0ebb91d476f95209394654850641ba0cdaeae31762602866fbe10fa1dccb08471

test:
  secret_key_base: 68505862940cf2eb3337fbc0bb7760a7e53fcb33b306cb451ceece407cae4faeed758da0324219d0c36fa921de6592538de2824842b954ae6ff66ac74d36f12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
